version: '3.8'

services:
zoo1:
api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:3000
    command: yarn start:debug
volumes:
      - /type-orm/node_modues
      - ./src
depends_on:
      - redis
env_file: .env

redis:
image: 'redis:alpine'
ports: 
- 6379:${REDIS_PORT}